version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-web
    ports:
      - "5000:5000"
    volumes:
      - .:/app
  cli:
    build:
      context: .
      dockerfile: Dockerfile-cli
    volumes:
      - .:/cli
